#pragma once
/*
 * This file was autogenerated by EmbeddedMPC on May 30, 2022 at 12:26:34.
 * 
 * This file contains the data for the MPC problem
 */

#include <EmbeddedMPC.h>

const int nstates = 12;
const int ninputs = 4;
const int nhorizon = 11;
extern c_float dynamics_Adata[144];
extern c_float dynamics_Bdata[48];
extern c_float dynamics_fdata[12];
extern c_float cost_Qdata[12];
extern c_float cost_qdata[12];
extern c_float cost_Rdata[4];
extern c_float cost_rdata[4];
extern c_float cost_Qfdata[12];
extern c_float cost_qfdata[12];
const c_float cost_c = 0.0;
